### ISSUE TITLE
Turning off

### ISSUE THREAD

**Issue by thoward27** [thoward27/self-driving-taxi-section01#16]
# Turn off
        
        ### Branch:
        func_turn_off
        
        ### Should:
        - Turn the car off
        - Set RPM to 0
        - Turn off all lights
        - Lock the car
        
        ### Relies on:
        - unlock()
        - toggle_lights()

**Comment by Abrar501** [comment]
Abrar MAlik, Fehmina Hasan

**Comment by fehminah** [comment]
Abrar501 will be doing the pull request
